using System;
using System.Collections.Generic;
using System.Text;

namespace MyPasswordManager
{
    public static class MyRandom
    {
        public static string Chars = "EmmaOliviaAvaIsabellaSophiaCharlotteMiaAmeliaHarpe45678rEvelynAbigailEmilyElizabethMilaEllaAverySofiaCamilaA54678riaSca@@@rlettVictoriaLunaGraceChloePenelopeLaylaRileyZoeyNoraLilyHannahLillianAubre@yEllieStellaNa22233talieZoeLeahHazelVioletAuroraSavannahAudreyBrooklynBellaClaireSsdfg234569087kylarLiamNoahWilliamJamesOliverBenjaminElijahLucasMasonLoganAlexanderEthanJacobMichaelDanielHenryJacksonSebastianAidenMatthewSamuelD12345670987lkjhgavidJosephCarterOwenWyattJohnJack@@@LukeJaydenDylanLeviIsaacGabrielJulianMateoAnthonyLincolnJoshuaChristopherTheodoreC56789alebRyanAsherNatha567823nThomasLeo";

    }
}
