using System;
using System.Collections.Generic;
using System.Text;

namespace MyPasswordManager
{
    public static class MyRandom
    {
        public static string Chars = "EmmaOreinerliviaAva34533IsabellaSophiaCharlotte0532MiaAmeliaHarpe45678rEvelynAbigailEmilyElizabethMilaEllaAverySofiaCamilaA54678riaSca@@@rlettVictoriaLunaGraceChloePenelopeLaylaRileyZoey0503NoraLilyHannahLillianAubre@yEllieStellaNa22233talieZoeLeahHazelVioletAuroraSavannahAudreyBrooklynBellaClaireSsdfg234569087kylarLiamNoahWilliamJamesOliverBenjaminElijahLucasMasonLoganAlexanderEthanJacobMichaelDanielHenryJacksonSebastianAidenMatthewSamuelD12345670987lkjhgavidJosephCarterOwenWyattJohnJack@@@LukeJaydenDylanLeviIsaacGabrielJulianMateoAnthonyLincolnJoshuaChristopherTheodoreC56789alebRyanAsherNatha567823nThomasLeo";

    }
}
